---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vm-import-operator
  namespace: kubevirt-hyperconverged

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: vm-import-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - services/finalizers
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - vm-import-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - replicasets
  verbs:
  - get
- apiGroups:
  - v2v.kubevirt.io
  resources:
  - '*'
  - resourcemappings
  - vmimportconfigs
  verbs:
  - '*'
- apiGroups:
  - kubevirt.io
  resources:
  - virtualmachines
  - virtualmachines/finalizers
  - virtualmachineinstances
  verbs:
  - '*'
- apiGroups:
  - cdi.kubevirt.io
  resources:
  - datavolumes
  verbs:
  - '*'
- apiGroups:
  - template.openshift.io
  resources:
  - templates
  verbs:
  - get
- apiGroups:
  - template.openshift.io
  resources:
  - processedtemplates
  verbs:
  - create
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
  - list
  - watch

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vm-import-operator
roleRef:
  kind: ClusterRole
  name: vm-import-operator
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: vm-import-operator
  namespace: kubevirt-hyperconverged

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vm-import-operator
  namespace: kubevirt-hyperconverged
spec:
  replicas: 1
  selector:
    matchLabels:
      name: vm-import-operator
  template:
    metadata:
      labels:
        name: vm-import-operator
    spec:
      serviceAccountName: vm-import-operator
      containers:
        - name: vm-import-operator
          # Replace this with the built image name
          image: quay.io/masayag/vm-import-operator:v0.0.2
          command:
          - vm-import-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "vm-import-operator"
